CREATE TABLE GUESTS
(
	GUESTID INT NOT NULL AUTO_INCREMENT,
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
	--olderThan21 TINYINT NOT NULL,
	
	GUEST_FID INT,
	
	primary key (GUESTID),
	FOREIGN KEY (GUEST_FID) REFERENCES GUESTS_FAMILY(GUEST_FID)
	
	
);

CREATE TABLE GUESTS_FAMILY
(
	GUEST_FID INT NOT NULL AUTO_INCREMENT,
	--FirstName VARCHAR(100) NOT NULL,
	--LastName VARCHAR(100) NOT NULL,
	PhoneNumber VARCHAR(100) NOT NULL,
	Email VARCHAR(100),
	
	
	Address VARCHAR(255) NOT NULL,
	PostalCode VARCHAR(100) NOT NULL,
	City VARCHAR(100) NOT NULL,
	State VARCHAR (10),
	Country VARCHAR (100) NOT NULL,
	
	
	primary key (GUEST_FID)
	

);
CREATE TABLE RSVP_INFO
(
	RSVPID  INT NOT NULL AUTO_INCREMENT,
	AllowedSeats INT NOT NULL,
	IsRSVP TINYINT(1) NOT NULL,
	IsConfirmed TINYINT(1) NOT NULL, -- we recieve email and we have to approve
	Seats_RSVPd INT NOT NULL,
	
	GUEST_FID INT,
	
	primary key (RSVPID),
	FOREIGN KEY (GUEST_FID) REFERENCES GUESTS_FAMILY(GUEST_FID)
	
);

CREATE TABLE LOG_INFO
(
	LOGID  INT NOT NULL AUTO_INCREMENT,
	Createddate VARCHAR(100) NOT NULL,
	Updateddate VARCHAR(100),
	LocationIP VARCHAR(100),
	
	
	
	GUEST_FID INT,
	primary key (LOGID),
	FOREIGN KEY (GUEST_FID) REFERENCES GUESTS_FAMILY(GUEST_FID)
	
);
